add threshold check in travis yaml file.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -24,10 +24,11 @@ matrix:
           - python-setuptools
           - python3-pip
           - python3-setuptools
+          - valgrind
 
     before_install:
       - sudo apt update -y -qq
-      - sudo apt install -y net-tools python-pip python-setuptools python3-pip python3-setuptools
+      - sudo apt install -y net-tools python-pip python-setuptools python3-pip python3-setuptools valgrind
 
     before_script:
       - cd ${TRAVIS_BUILD_DIR}
@@ -43,16 +44,32 @@ matrix:
         case $TRAVIS_OS_NAME in
           linux)
           cd ${TRAVIS_BUILD_DIR}/debug
-          sudo make install || exit $?
+          sudo make install || travis_terminate $?
 
           pip install --user ${TRAVIS_BUILD_DIR}/src/connector/python/linux/python2/
           pip3 install --user ${TRAVIS_BUILD_DIR}/src/connector/python/linux/python3/
 
           cd ${TRAVIS_BUILD_DIR}/tests
-          bash ./test-all.sh
+          ./test-all.sh || travis_terminate $?
 
-          if [ "$?" -ne "0" ]; then
-            exit $?
+          cd ${TRAVIS_BUILD_DIR}/tests/pytest
+          ./simpletest.sh -g 2>&1 | tee mem-error-out.txt
+          sleep 1
+
+          # Color setting
+          RED='\033[0;31m'
+          GREEN='\033[1;32m'
+          GREEN_DARK='\033[0;32m'
+          GREEN_UNDERLINE='\033[4;32m'
+          NC='\033[0m'
+
+          mem_error=`grep -m 1 'ERROR SUMMARY' mem-error-out.txt | awk '{print $4}'`
+
+          if [ -n "$mem_error" ]; then
+            if [ "$mem_error" -gt 20 ]; then
+              echo -e "${RED} ## Memory errors number valgrind reports is $mem_error. More than our threshold! ## ${NC} "
+              travis_terminate $mem_error
+            fi
           fi
 
           ;;
@@ -132,17 +149,17 @@ matrix:
         case $TRAVIS_OS_NAME in
           linux)
           cd ${TRAVIS_BUILD_DIR}/debug
-          sudo make install || exit $?
+          sudo make install || travis_terminate $?
 
           pip install --user ${TRAVIS_BUILD_DIR}/src/connector/python/linux/python2/
           pip3 install --user ${TRAVIS_BUILD_DIR}/src/connector/python/linux/python3/
 
           cd ${TRAVIS_BUILD_DIR}/tests
 
-          bash ./test-all.sh
+          ./test-all.sh
 
           if [ "$?" -ne "0" ]; then
-            exit $?
+            travis_terminate $?
           fi
 
           sudo pkill taosd
@@ -150,7 +167,7 @@ matrix:
 
           cd ${TRAVIS_BUILD_DIR}
           lcov -d . --capture --rc lcov_branch_coverage=1 -o coverage.info
-          lcov -l --rc lcov_branch_coverage=1 coverage.info || exit $?
+          lcov -l --rc lcov_branch_coverage=1 coverage.info || travis_terminate $?
 
           gem install coveralls-lcov
 
@@ -166,7 +183,6 @@ matrix:
             echo -e "${GREEN} ## Uploaded to Coveralls.io! ## ${NC}"
           else
             echo -e "${RED} ## Coveralls.io not collect coverage report! ## ${NC} "
-            exit $?
           fi
 
           bash <(curl -s https://codecov.io/bash) -y .codecov.yml -f coverage.info
@@ -174,7 +190,6 @@ matrix:
             echo -e "${GREEN} ## Uploaded to Codecov! ## ${NC} "
           else
             echo -e "${RED} ## Codecov did not collect coverage report! ## ${NC} "
-            exit $?
           fi
 
           ;;
