add simplest pytest for 2.0

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -50,6 +50,15 @@ script:
   - |-
     case $TRAVIS_OS_NAME in
       linux)
+        # Color setting
+        RED='\033[0;31m'
+        GREEN='\033[1;32m'
+        GREEN_DARK='\033[0;32m'
+        GREEN_UNDERLINE='\033[4;32m'
+        NC='\033[0m'
+
+        sudo make install
+
         cd ../tests/script
         sudo ./test.sh 2>&1 | grep 'success\|failed' | tee out.txt
 
@@ -57,16 +66,32 @@ script:
 
         if [ "$total_success" -gt "0" ]; then
           total_success=`expr $total_success - 1`
+          echo -e "${GREEN}$ Total $total_success success${NC}"
         fi
-
-        echo "Total $total_success success"
 
         total_failed=`grep failed out.txt | wc -l`
-        echo "Total $total_failed failed"
-
         if [ "$total_failed" -ne "0" ]; then
+          echo -e "${RED}Total $total_failed failed${NC}"
           exit $total_failed
         fi
+
+        pip install --user ../../src/connector/python/linux/python2/ 
+        pip3 install --user ../../src/connector/python/linux/python3/ 
+
+        cd ../pytest
+        sudo ./simpletest.sh 2>&1 | grep 'successfully executed\|failed' | tee pytest-out.txt
+        total_py_success=`grep 'successfully executed' pytest-out.txt | wc -l`
+
+        if [ "$total_py_success" -gt "0" ]; then
+          echo -e "${GREEN}Total $total_py_success python case(s) success${NC}"
+        fi
+
+        total_py_failed=`grep 'failed' pytest-out.txt | wc -l`
+        if [ "$total_py_failed" -ne "0" ]; then
+          echo -e "${RED}Total $total_py_failed python case(s) failed${NC}"
+          exit $total_py_failed
+        fi
+
         ;;
     esac
 
@@ -81,6 +106,8 @@ matrix:
           - build-essential
           - cmake
           - net-tools
+          - python-pip
+          - python3-pip
 
 #  - os: osx
 #    addons:
